apiVersion: v1
kind: Template
labels:
  template: fluentd-splunk-forwarder-template
message: A Fluentd Splunk Forwarder has been created
metadata:
  annotations:
    description: Fluentd Splunk Forwarder Agent
    iconClass: icon-jenkins
    tags: instant-app,fluentd-splunk
  name: fluentd-splunk-forwarder-template
  namespace: openshift
objects:
- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    name: "fluentd-splunk-forwarder"
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "fluentd-splunk-forwarder"
  spec:
    triggers:
      - type: ConfigChange
      - type: ImageChange
    source:
      type: Git
      git:
        uri: https://github.com/makentenza/ocp-fluentd-splunk.git
    strategy:
      type: "Docker"
      dockerStrategy:
        from:
          kind: "DockerImage"
          name: "registry.access.redhat.com/openshift3/logging-fluentd:3.3.1"
    output:
      to:
        kind: "ImageStreamTag"
        name: "fluentd-splunk-forwarder:latest"
